(function (){
	"use strict";
	
	var reader = new XMLHttpRequest(), url = "", art = "", line = 0, then = "", fromCache = false, warnText = "", type = 0, types = [], fullblock = false, rval = "", 
	tab = window.location.toString(), ael = 0, aels = document.getElementsByTagName('a'), now = new Date(), blockLists = [], fullList = "", i = 0;
	var weekFromNow = new Date(now.getTime() + 604800000);
	now.setHours(0,0,0,0);
		
	function checkList(listText, listURL) {
		var lines = listText.split('\n');
		var errorCount = 0;
		
		for (line = 0; line < lines.length; line++) {
			if ((lines[line]).split(',')[0] == null) {
				console.error("Blocklist syntax error on line " + line + ": first argument (Domain URL) is missing! Origin: " + listURL);
				errorCount++;
			} else if (!(lines[line]).split(',')[1] == null) {
				console.error("Blocklist syntax error on line " + line + ": second argument (Proof URL) is missing! Origin: " + listURL);
				errorCount++;
			} else if (!(lines[line]).split(',')[2] == null) {
				console.error("Blocklist syntax error on line " + line + ": first argument (Domain type) is missing! Origin: " + listURL);
				errorCount++;				
			} else if (errorCount > 0) {
				return false;
			} else {
				return true;
			}
		}
	}
	
	function retrieve(key) {
		chrome.storage.local.get(key, function(result){
			rval = result[key];
		});	return rval;
	}
	
	// Retrieve all the lists as set in options. If none are set load the default list from our Github repo
	function getLists() {
		chrome.storage.sync.get({
			lists: "https://raw.githubusercontent.com/Fdebijl/FakeNewsBlocker/master/blocklist.txt",
			types: [1,2],
			fullblock: false
		}, function(items) {

			if (items.lists.split(/\r\n|\r|\n/).length > 1) {
				blockLists = (items.lists.split('\n'));
			} else {
				blockLists = [items.lists];
			}
			types = items.types;
			fullblock = items.fullblock;

			if (blockLists.join() != retrieve("FakeNews_prevlist")) {
				// Setting has changed since we last imported the blocklists, time to craft a new master list
				loadFile(1);
			} else {
				loadFile();	
			}	
		});
		
	
	}
	
	// Import the blocklists as generated by getLists
	function loadFile(skipCheck) {		
		if (retrieve("FakeNews_blocklist") != null && skipCheck !== 1) {
			then = retrieve("FakeNews_expires");
			if (then < now || typeof(then) == null) {
				loadFile(1);
			} else {
				fromCache = true;
				matchURL();
			}
		} else {
			for (i = 0; i < blockLists.length; i++) {
				reader.open('get', blockLists[i], true); 
				reader.onreadystatechange = function() {
					if(reader.readyState === 4) {
						if (checkList(reader.responseText, blockLists[i]) === false) {
							alert("One of your blocklists contains invalid syntax and may cause errors! Check the log (F12) for more details.");
						}
						
						if (i > 0) {
							fullList += "\n" + reader.responseText;	
						} else {
							fullList += reader.responseText;	
						}
						
							
						if (i === blockLists.length) {
							chrome.storage.local.set({
								'FakeNews_blocklist': fullList,
								'FakeNews_expires': weekFromNow.toString,
								'FakeNews_prevlist': blockLists.join()
							}, function() {
								matchURL();
							});
						}		
					}
				};
				reader.send(null);
			}
		}
	} 
	
	window.onload = function() {
		getLists();
		document.styleSheets[0].addRule('.FakeNews_link:before','content: url(https://github.com/Fdebijl/FakeNewsBlocker/raw/master/logo16_fake.png); display: inline !important; visibility: visible !important; height: 1em !important; width: 1em !important; z-index: 999999999 !important; padding: .3em !important; ');
	};

	function getPat(u) {
		u = u.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
		return new RegExp('(http|https)(:\/\/)(.+|)(' + u + ')', 'i');
	}
	
	function matchURL() {
		var lines = fromCache ? retrieve("FakeNews_blocklist").split('\n') : fullList.split('\n');
		console.log("Lines: " + lines);
		warnText = fromCache ? "(from cache)" : "";
		for (line = 0; line < lines.length; line++) {
			url = (lines[line]).split(',')[0];
			art = (lines[line]).split(',')[1];
			if ((lines[line]).split(',')[2] != undefined) {
				type = (lines[line]).split(',')[2];	
			} else {
				type = 1;
			}
			
			if (tab.match(getPat(url)) && url !== "" && types.indexOf(type) > -1 && fullblock) {
				console.log("Fullblock initiated");
			} else if (tab.match(getPat(url)) && url !== "" && types.indexOf(type) > -1) {
				chrome.runtime.sendMessage({t: "notu", l: url});
				console.warn("Supplied proof " + warnText + ": " + art);
			}
			
			for (ael = 0; ael < aels.length; ael++) {
                if((aels[ael].href).match(getPat(url)) && url !== "" && (aels[ael].href) !== "" && url !== location.host.replace('www.','') && types.indexOf(type) > -1) {
					aels[ael].className += " FakeNews_link"; 
					aels[ael].setAttribute('title', "Possible fake news");
				}	
			}
    	}
	}
})();